"""initial

Revision ID: 457b06cd11cc
Revises: 
Create Date: 2026-05-07 22:46:26.604811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '457b06cd11cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('generation_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('ratio_requested', sa.String(), nullable=False),
    sa.Column('resolution_requested', sa.String(), nullable=False),
    sa.Column('duration_requested', sa.Integer(), nullable=True),
    sa.Column('generate_audio', sa.Boolean(), nullable=False),
    sa.Column('watermark', sa.Boolean(), nullable=False),
    sa.Column('seed_requested', sa.Integer(), nullable=True),
    sa.Column('content_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('last_frame_url', sa.String(), nullable=True),
    sa.Column('duration_actual', sa.Integer(), nullable=True),
    sa.Column('ratio_actual', sa.String(length=16), nullable=True),
    sa.Column('resolution_actual', sa.String(length=16), nullable=True),
    sa.Column('seed_actual', sa.Integer(), nullable=True),
    sa.Column('framespersecond', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_tasks_external_id'), 'generation_tasks', ['external_id'], unique=True)
    op.create_index(op.f('ix_generation_tasks_status'), 'generation_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_generation_tasks_user_id'), 'generation_tasks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generation_tasks_user_id'), table_name='generation_tasks')
    op.drop_index(op.f('ix_generation_tasks_status'), table_name='generation_tasks')
    op.drop_index(op.f('ix_generation_tasks_external_id'), table_name='generation_tasks')
    op.drop_table('generation_tasks')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
