"""add enhance_tasks upscale_resolution

Revision ID: 7286c2e95b70
Revises: f13f71ffab1a
Create Date: 2026-05-15 10:25:33.472234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7286c2e95b70'
down_revision: Union[str, Sequence[str], None] = 'f13f71ffab1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enhance_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('generation_task_id', sa.UUID(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('source_width', sa.Integer(), nullable=False),
    sa.Column('source_height', sa.Integer(), nullable=False),
    sa.Column('source_fps', sa.Float(), nullable=False),
    sa.Column('source_duration', sa.Float(), nullable=False),
    sa.Column('source_frame_count', sa.Integer(), nullable=False),
    sa.Column('source_size', sa.Integer(), nullable=False),
    sa.Column('source_container', sa.String(length=16), nullable=False),
    sa.Column('output_resolution', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('local_path', sa.String(), nullable=True),
    sa.Column('download_url', sa.String(), nullable=True),
    sa.Column('expires_in_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['generation_task_id'], ['generation_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enhance_tasks_generation_task_id'), 'enhance_tasks', ['generation_task_id'], unique=False)
    op.create_index(op.f('ix_enhance_tasks_request_id'), 'enhance_tasks', ['request_id'], unique=True)
    op.create_index(op.f('ix_enhance_tasks_status'), 'enhance_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_enhance_tasks_user_id'), 'enhance_tasks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enhance_tasks_user_id'), table_name='enhance_tasks')
    op.drop_index(op.f('ix_enhance_tasks_status'), table_name='enhance_tasks')
    op.drop_index(op.f('ix_enhance_tasks_request_id'), table_name='enhance_tasks')
    op.drop_index(op.f('ix_enhance_tasks_generation_task_id'), table_name='enhance_tasks')
    op.drop_table('enhance_tasks')
    # ### end Alembic commands ###
